- .github/workflows/copy-labels.yml
> Added copy labels from issues to PR
Fixes #2
> feat: added copy labels to pr workflow

- .github/workflows/publish-ds-release-alpha.yml
This workflow will create and publish an alpha version of the package to NPM on push to release.
> feat: Workflow - Publish prerelease alpha package to NPM

- .github/workflows/publish-ds-release-alpha.yml
- Fixes for failing workflow because of git config.
- Added check for folder content change
Fixes [#14705](https://github.com/appsmithorg/appsmith/issues/14705)
> fix: Fix for failed release workflow

- .github/workflows/publish-ds-release-alpha.yml
Changed the default directory to packages/design-system
Fixes [#14705](https://github.com/appsmithorg/appsmith/issues/14705)
> fix: Changed workflow directory for release alpha

- packages/design-system/README.md
> fix: Readme homepage URL fix

- packages/design-system/README.md
> fix: URL change

- .changeset/changed-readme-25fd226.md
- packages/design-system/README.md
> feat: Changed Readme

- .changeset/moody-socks-yell.md
- packages/design-system/README.md
> fix: Readme file changed

- .github/workflows/ds-storybook-deploy.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
Added workflow to build static file for storybook deployment
Fixes [#14936](https://github.com/appsmithorg/appsmith/issues/14936)
> ci: Added workflow for Storybook deployment

- .github/workflows/ds-storybook-deploy.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
* Added workflow for Storybook deployment
* Add upload to S3 step
* Workflows node setup version updated
* Changed static file path
* Added secret variable for aws role
Co-authored-by: Shrikant Sharat Kandula <shrikantsharat.k@gmail.com>
>
> and context. List any dependencies that are required for this change.
- New feature (non-breaking …
> ci: Added workflow for Storybook deployment (#20)

- .github/workflows/beta.yml
- .github/workflows/prerelease.yml
Added changeset for beta release
> ci: Added changeset for beta release

- packages/design-system/README.md
Added documentation regarding how to add css
> fix: Readme - css include documentation added

- .github/workflows/ds-storybook-deploy.yml
Fixed broken workflow for storybook.
Fixes
> fix: Storybook workflow fixed

- .changeset/clean-radios-accept.md
- packages/design-system/README.md
Fixed the spacing issue in readme file. Also, this PR is to test the workflows.
Fixes [#15001](https://github.com/appsmithorg/appsmith/issues/15001)
> fix: Fixed spacing in readme

- .changeset/nasty-bugs-matter.md
- packages/design-system/README.md
Readme changed
Fixes [#15001](https://github.com/appsmithorg/appsmith/issues/15001)
> fix: Readme change for testing workflows

- .github/workflows/beta.yml
Workflow fixes
Fixes [#15019](https://github.com/appsmithorg/appsmith/issues/15019)
> fix: Beta release workflow fix

- .changeset/tasty-bikes-beam.md
- packages/design-system/README.md
Readme change for testing workflow
Fixes [#15001](https://github.com/appsmithorg/appsmith/issues/15001)
> fix: Readme change for testing workflow

- .changeset/breezy-cougars-smoke.md
- packages/design-system/rollup.config.js
- packages/design-system/src/DropdownV2/index.tsx
- packages/design-system/src/index.ts
Fixes issues with incorrect exports
- 
yalc has been used to link and test the package on my local machine.
> fix: issues in the migration of dropdown v2

- packages/design-system/src/Switcher/Switcher.stories.tsx
- packages/design-system/src/Switcher/index.tsx
- packages/design-system/src/index.ts
Migrated Switcher component and added story.
Fixes [#15225](https://github.com/appsmithorg/appsmith/issues/15225)
> feat: Migration - Switcher component

- .changeset/smart-jeans-cheat.md
- packages/design-system/src/ColorPicker/index.tsx
- packages/design-system/src/Switch/Switch.stories.tsx
- packages/design-system/src/Switch/index.tsx
- packages/design-system/src/index.ts
Migrated switch component and added story.
Fixes [#15224](https://github.com/appsmithorg/appsmith/issues/15224)
> feat: Migration - Switch component

- .changeset/grumpy-brooms-tan.md
- packages/design-system/src/Menu/Menu.stories.tsx
- packages/design-system/src/Menu/index.tsx
- packages/design-system/src/MenuItem/index.tsx
- packages/design-system/src/constants/Icon.tsx
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/colors.css
- packages/design-system/src/themes/default/variables.css
Migrated Menu and Menu Item component and added story for Menu
Fixes [#15223](https://github.com/appsmithorg/appsmith/issues/15223)
> feat: Migration - Menu, Menu Item component

- .changeset/plenty-keys-suffer.md
- packages/design-system/alpha-release.sh
- packages/design-system/package.json
- packages/design-system/src/AppIcon/index.tsx
- packages/design-system/src/Button/Button.stories.tsx
- packages/design-system/src/Button/index.tsx
- packages/design-system/src/common/index.ts
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/colors.css
- packages/design-system/tsconfig.json
- yarn.lock
Migrated button component and added story
Fixes [#15222](https://github.com/appsmithorg/appsmith/issues/15222)
> feat: Migration - Button component

- packages/design-system/.npmignore
- packages/design-system/README.md
- packages/design-system/create_story.sh
- packages/design-system/package.json
- packages/design-system/src/TagInput/TagInput.stories.tsx
- packages/design-system/src/TagInput/index.tsx
- packages/design-system/src/common/index.ts
- packages/design-system/src/constants/messages.tsx
- packages/design-system/src/themes/default/colors.css
- packages/design-system/src/themes/default/index.css
- packages/design-system/story_template.txt
Migrated Tag Input component from main repository along with written story for the component. Also, added scripts to create a story template.
Fixes [#15276](https://github.com/appsmithorg/appsmith/issues/15276)
- Tested using storybook
> feat: Migrated Tag Input component

- .changeset/nervous-knives-love.md
- packages/design-system/README.md
- packages/design-system/package.json
- packages/design-system/src/MenuDivider/MenuDivider.stories.tsx
- packages/design-system/src/MenuDivider/index.tsx
- packages/design-system/src/Radio/Radio.stories.tsx
- packages/design-system/src/Radio/index.tsx
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/index.css
- packages/design-system/src/themes/default/variables.css
- yarn.lock
This PR closes the issue https://github.com/appsmithorg/appsmith/issues/15199. Migrates RadioComponent and Menu Divider component.
- 
on storybook
> feat: Migration - radio, divider

- .changeset/shiny-kangaroos-walk.md
- packages/design-system/src/ColorSelector/ColorSelector.stories.tsx
- packages/design-system/src/ColorSelector/index.tsx
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/index.css
Will migrate color selector component from the ads folder. Fixes https://github.com/appsmithorg/appsmith/issues/15291
Tested on Storybook
> feat: Create ColorSelector

- .changeset/tiny-tips-love.md
- packages/design-system/package.json
- packages/design-system/src/Breadcrumbs/Breadcrumbs.stories.tsx
- packages/design-system/src/Breadcrumbs/index.tsx
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/colors.css
- packages/design-system/src/themes/default/index.css
- yarn.lock
Migrated Breadcrumbs component from main repository and added story for the same.
Fixes [#15285](https://github.com/appsmithorg/appsmith/issues/15285)
- Tested with storybook
> feat: Migrate breadcrumbs component and story

- .changeset/forty-forks-pretend.md
- packages/design-system/src/Callout/Callout.stories.tsx
- packages/design-system/src/Callout/index.tsx
- packages/design-system/src/constants/variants.ts
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/index.css
Migrates callout from ads to design-system. Closes https://github.com/appsmithorg/appsmith/issues/15289
On storybook
> feat: migrate callout

- .changeset/happy-cameras-pretend.md
- packages/design-system/src/TextInput/TextInput.stories.tsx
- packages/design-system/src/TextInput/index.tsx
- packages/design-system/src/constants/messages.tsx
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/index.css
Migrates Text Input component too the design system. Fixes https://github.com/appsmithorg/appsmith/issues/15305
On storybook
> feat: migrate text input

- .changeset/lazy-lamps-remember.md
- packages/design-system/package.json
- packages/design-system/src/CopyToClipboard/CopyToClipboard.stories.tsx
- packages/design-system/src/CopyToClipboard/index.tsx
- packages/design-system/src/index.ts
- yarn.lock
Migrates copy to clipboard. This PR closes https://github.com/appsmithorg/appsmith/issues/15293
On Storybook
> feat: migrate copy to clipboard

- packages/design-system/src/Toggle/Toggle.stories.tsx
- packages/design-system/src/Toggle/index.tsx
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/colors.css
- packages/design-system/src/themes/default/index.css
Migrated Toggle component from main repository and added story.
Fixes [#15287](https://github.com/appsmithorg/appsmith/issues/15287)
- Tested using storybook
> feat: Migrate Toggle component from main repository

- .changeset/heavy-shirts-try.md
- packages/design-system/src/ButtonTab/ButtonTab.stories.tsx
- packages/design-system/src/ButtonTab/index.tsx
- packages/design-system/src/hooks/index.tsx
- packages/design-system/src/hooks/useDSEvent.ts
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/colors.css
- packages/design-system/src/themes/default/index.css
- packages/design-system/src/types/common.ts
Migrated Button tab component from main repo. Added story for the same
Fixes [#15286](https://github.com/appsmithorg/appsmith/issues/15286)
- Tested using storybook
> feat: Migrated ButtonTab component, Added story

- .changeset/fifty-eyes-matter.md
- packages/design-system/src/LabelWithTooltip/LabelWithTooltip.stories.tsx
- packages/design-system/src/LabelWithTooltip/index.tsx
- packages/design-system/src/constants/typography.ts
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/index.css
- packages/design-system/src/types/common.ts
This PR will migrate Label with tooltip.  Fixes https://github.com/appsmithorg/appsmith/issues/15398
On Storybook
> feat: migrate label with tooltip

- packages/design-system/src/TreeDropdown/TreeDropdown.stories.tsx
- packages/design-system/src/TreeDropdown/index.tsx
- packages/design-system/src/common/hooks/useDSEvent.ts
- packages/design-system/src/themes/default/index.css
Migrates Tree dropdown.
Fixes https://github.com/appsmithorg/appsmith/issues/15401
On storybook
> feat: add tree dropdown

- packages/design-system/src/themes/default/colors.css
Added missing black color css variable.
Fixes [#15413](https://github.com/appsmithorg/appsmith/issues/15413)
> fix: missing variable of color black added

- .changeset/mean-carrots-glow.md
- packages/design-system/src/Checkbox/index.tsx
- packages/design-system/src/themes/default/index.css
This PR adds the updates from this commit: https://github.com/appsmithorg/appsmith/commit/a97ab3d9a2af438a60fed8308517efe34cfdea9e to the design system so that the component can be fully migrated. Contributes towards closing this issue: https://github.com/appsmithorg/appsmith/issues/15492
This PR will need to be merged and the package released before the builds connected with this will pass successfully
> feat: support primary and secondary variants in checkbox

- .changeset/light-donuts-study.md
- packages/design-system/src/CloseButton/CloseButton.stories.tsx
- packages/design-system/src/CloseButton/index.tsx
- packages/design-system/src/NotificationBanner/NotificationBanner.stories.tsx
- packages/design-system/src/NotificationBanner/index.tsx
- packages/design-system/src/constants/messages.tsx
- packages/design-system/src/themes/default/colors.css
- packages/design-system/src/themes/default/index.css
This PR migrates NotificationBanner, and CloseButton from the `designSystems` repo which it depends upon. Fixes https://github.com/appsmithorg/appsmith/issues/15403
On Storybook
> feat: migrate notification banner

- .changeset/friendly-drinks-scream.md
- packages/design-system/Component-Migration-Checklist.md
Adds note about comparing files to the checklist
> feat: update component migration checklist

- packages/design-system/src/TextInput/index.tsx
> fix: remove theme as a prop from TextInput

- packages/design-system/src/LabelWithTooltip/index.tsx
- packages/design-system/src/TextInput/index.tsx
This PR allows yarn to build the repo completely 
build now runs
> fix: typescript issues to allow build to complete

- packages/design-system/jest.config.js
- packages/design-system/jest.setup.ts
- packages/design-system/package.json
- packages/design-system/rollup.config.js
- packages/design-system/src/ButtonTab/ButtonTab.test.tsx
- packages/design-system/src/Dropdown/Dropdown.test.tsx
- packages/design-system/src/Icon/Icon.test.tsx
- packages/design-system/src/Icon/index.tsx
- packages/design-system/src/TableDropdown/index.tsx
- packages/design-system/src/Tabs/index.tsx
- packages/design-system/src/TreeDropdown/TreeDropdown.test.tsx
- packages/design-system/src/TreeDropdown/index.tsx
- packages/design-system/tsconfig.json
- yarn.lock
PR includes the configuration and the test files for jest. Also, fixed SVGR viewBox timing of issue.
Fixes [#15526](https://github.com/appsmithorg/appsmith/issues/15526)
- Tested the jest by running yarn test
- Checked build folder foe icon viewBox
> fix: Jest configuration, svgr viewbox fix

- .changeset/little-books-obey.md
- packages/design-system/src/ScrollIndicator/index.tsx
This PR updates ScrollIndicator behavior as detailed in PR https://github.com/appsmithorg/appsmith/pull/15573/files
> feat: update scroll indicator on hover behavior

- .changeset/four-bees-perform.md
- packages/design-system/src/HighlightText/index.tsx
This PR updates HighlightText to use better regex
> chore: update HighlightText from ee

- .changeset/four-bees-perform.md
- .changeset/little-books-obey.md
- packages/design-system/CHANGELOG.md
- packages/design-system/package.json
>
> and context. List any dependencies that are required for this change.
> Please describe the tests that you ran to verify your …
> feat: Changeset release/main

- .changeset/yellow-wasps-work.md
- packages/design-system/src/Button/Button.test.tsx
Add jest test for button component
Fixes [#15822](https://github.com/appsmithorg/appsmith/issues/15822)
> feat: Added button test

- packages/design-system/src/TableDropdown/index.tsx
update DropdownOption to TableDropdownOption and export for typechecking ease
> feat: update table dropdown type names

- .changeset/hungry-planes-breathe.md
- packages/design-system/src/Dropdown/index.tsx
- packages/design-system/src/LabelWithTooltip/index.tsx
- packages/design-system/tsconfig.json
sync LabelWithTooltip and Dropdown with ce
> chore: sync new ads updates

- .changeset/neat-trains-rush.md
- packages/design-system/src/Button/index.tsx
- packages/design-system/src/Callout/index.tsx
- packages/design-system/src/Dropdown/index.tsx
- packages/design-system/src/TagInput/index.tsx
This PR have the new changes made in [#15957](https://github.com/appsmithorg/appsmith/pull/15957)
Fixes [#15335](https://github.com/appsmithorg/appsmith/issues/15335)
> feat: Design system changes from PR #15957

- packages/design-system/src/TagInput/index.tsx
Design system build was failing due to the use of default import. Fixed the same.
Fixes [#15335](https://github.com/appsmithorg/appsmith/issues/15335)
- Tested build in local
> fix: changed import for highlight text

- packages/design-system/src/Icon/index.tsx
This syncs changes in Icon from https://github.com/appsmithorg/appsmith-ee/pull/486/files to the ds
> chore: Sync changes from ee 486 with ds

- .changeset/rotten-fishes-push.md
- packages/design-system/src/Checkbox/index.tsx
- packages/design-system/src/Dropdown/index.tsx
- packages/design-system/src/common/index.ts
- packages/design-system/src/themes/default/index.css
Will close https://github.com/appsmithorg/appsmith/issues/16123
> fix: ui issues with checkbox, button, dropdown

- packages/design-system/CHANGELOG.md
- packages/design-system/package.json
Conflict fix between main and release
> fix: fixing conflict between main and release

- .changeset/clean-carrots-explain.md
- packages/design-system/src/UneditableField/index.tsx
This PR fixes uneditable field and fixes the story
> fix: uneditable field icon

- .changeset/small-humans-remain.md
- packages/design-system/src/MenuDivider/index.tsx
- packages/design-system/src/themes/default/index.css
The color of menu divider is now accurate
> fix: color of menu divider

- .changeset/clean-ladybugs-smash.md
- packages/design-system/src/MenuDivider/index.tsx
- packages/design-system/src/Radio/index.tsx
- packages/design-system/src/TableDropdown/index.tsx
- packages/design-system/src/themes/default/index.css
Fixes issues with spacing and colors in import batch 2
> fix: issues with import branch 2

- .changeset/rich-emus-turn.md
- packages/design-system/src/themes/default/index.css
Fixes https://github.com/appsmithorg/appsmith/issues/16471
> fix: radio button color

- .github/workflows/Lib-build-design-system.yml
- .github/workflows/integration-tests-command.yml
- .github/workflows/test-build-docker-image.yml
Setup push and PR workflow
Tested in fork
> test: Design system ci

- .changeset/kind-humans-listen.md
- packages/design-system/src/Radio/index.tsx
Support for Selected Option Elements
Fixes [#13445](https://github.com/appsmithorg/appsmith/issues/13445)
> feat: support for updated pagination designs - added selectedOptionElements

- .github/workflows/integration-tests-command.yml
fixed libbuilddesignsystem.yml
> ci: fixed libbuilddesignsystem.yml

- .github/workflows/integration-tests-command.yml
Update integration-tests-command.yml
> ci: Update integration-tests-command.yml

- .changeset/red-chairs-breathe.md
- packages/design-system/src/Dropdown/index.tsx
- packages/design-system/src/Icon/index.tsx
- packages/design-system/src/themes/default/index.css
This PR has the design fixes for the dropdown and the functional fixes as well.
Fixes [#16388](https://github.com/appsmithorg/appsmith/issues/16388)
> fix: Dropdown v1 design fixes

- packages/design-system/src/Dropdown/index.tsx
Added empty state for dropdown if no options exist
Fixes [#16388](https://github.com/appsmithorg/appsmith/issues/16388)
> fix: Added empty state for dropdown

- .changeset/fresh-ligers-knock.md
- README.md
- packages/design-system/src/Dropdown/Dropdown.stories.tsx
- packages/design-system/src/Dropdown/index.tsx
This PR addresses following issues
1. On the first try if we press space after entering any text in the dropdown, the space does not reflect in the search text.
2. If we select any option and then try to enter something in the search text and then press space, the dropdown closes.
Fixes [#16388](https://github.com/appsmithorg/appsmith/issues/16388)
> fix: Dropdown keyboard navigation

- .changeset/clever-meals-smell.md
- packages/design-system/src/CalloutV2/CalloutV2.stories.tsx
- packages/design-system/src/CalloutV2/index.tsx
- packages/design-system/src/NotificationBanner/index.tsx
- packages/design-system/src/UneditableField/UneditableField.test.tsx
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/colors.css
- packages/design-system/src/themes/default/index.css
Migrate Callout v2 while removing redux from it
> feat: migrate callout v2

- .changeset/yellow-dragons-attack.md
- packages/design-system/src/Dropdown/index.tsx
Reverting dropdown changes since it is breaking in main repo.
> fix: Reverted dropdown changes

- .changeset/green-panthers-destroy.md
- packages/design-system/src/UneditableField/index.tsx
This PR destructures the onClick prop on the UneditableField component. Fixes https://github.com/appsmithorg/appsmith/issues/16685
Locally
> fix: destructure props on uneditable field

- .changeset/slow-sheep-smash.md
- packages/design-system/src/Dropdown/Dropdown.stories.tsx
- packages/design-system/src/Dropdown/index.tsx
This PR fixes the keyboard navigation and UI fixes for dropdown
1. For single select dropdown keyboard navigation does not work if not option is selected.
2. For single select dropdown if an option is already selected and the we try to press the up/down arrow keys, the selected option disappears and we cannot navigate further.
3. For multi select dropdown clicking Enter does not select the options.
4. For multi select dropdown there is an infinite scroll i.e. if we press down arrow key after the last option, the first option does not get selected rather the highlight disappears.
5. There is a padding for dropdown option wrapper in the bottom.
Fixes [#16997](https://github.com/appsmithorg/appsmith/issues/16997)
- Tested in storybook.
- …
> fix: Dropdown keyboard navigation and UI fixes

- .github/workflows/integration-tests-command.yml
- .github/workflows/ok-to-test.yml
> ci: Enable oktotest

- .github/workflows/Lib-build-design-system.yml
- .github/workflows/integration-tests-command.yml
- packages/design-system/package.json
added support for chromatic
codereview
> ci: added support for chromatic

- .github/workflows/alpha.yml
This PR adds the workflow for releasing alpha version when a PR is raised to release branch
> ci: Alpha workflow

- .changeset/warm-candles-yell.md
- packages/design-system/src/index.ts
Fixes build on PR https://github.com/appsmithorg/appsmith/pull/17252
via alpha release
> fix: typo in export

- packages/design-system/src/FormGroup/index.tsx
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/index.css
Migrated form group component from main repo to design system
Fixes [#17198](https://github.com/appsmithorg/appsmith/issues/17198)
- Tested in local
> feat: form group component migration

- .changeset/pretty-hounds-repeat.md
- packages/design-system/src/ButtonTab/ButtonTab.stories.tsx
- packages/design-system/src/ButtonTab/index.tsx
Makes the ButtonTab component to accept label
> feat: Makes ButtonTab to accept label

- packages/design-system/src/FormMessage/FormMessage.stories.tsx
- packages/design-system/src/FormMessage/index.tsx
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/colors.css
- packages/design-system/src/themes/default/index.css
Migrates FormMessage from the ads folder. Progresses https://github.com/appsmithorg/appsmith/issues/17251, https://github.com/appsmithorg/appsmith/issues/15399
Locally, and on DP
> feat: migrate FormMessage

- .changeset/three-wolves-drop.md
- packages/design-system/src/Table/index.tsx
Fixed design issue of showing hover state for the row even if there is no data.
Fixes [#17328](https://github.com/appsmithorg/appsmith/issues/17328)
- Tested in local to ensure whether hover state is showing or not if there is no data
> fix: Table no data found hover state issue

- packages/design-system/src/Box/Box.stories.tsx
- packages/design-system/src/Box/index.tsx
- packages/design-system/src/MenuDivider/MenuDivider.stories.tsx
- packages/design-system/src/MenuDivider/index.tsx
- packages/design-system/src/index.ts
Fixes https://github.com/appsmithorg/appsmith/issues/17927
On storybook
> feat: add vertical menu divider

- packages/design-system/src/TreeDropdown/index.tsx
…with-pagelist"
This reverts commit fa81b5db700331300f23fc61ea8e0b3a06222b6c, reversing changes made to 175c1abe15e8cf1c73c89806cf0539ad1113e71c.
>
> and context. List any dependencies that are required for this change.
- Breaking change (fix or feature that would cause existing …
> fix: revert changes to tree dropdown

- .changeset/four-drinks-watch.md
>
> and context. List any dependencies that are required for this change.
> Please describe the tests that you ran to verify your …
> chore: add changeset for the previous PR

- .changeset/friendly-terms-tan.md
- packages/design-system/src/FormMessage/FormMessage.stories.tsx
- packages/design-system/src/FormMessage/index.tsx
Removed react router dom Link from form message component since it was not working as expected and was causing issue in main repo.
Fixes [#18086](https://github.com/appsmithorg/appsmith/issues/18086)
> fix: Form message component react router issue

- .changeset/eight-coins-sniff.md
- .changeset/fresh-windows-sort.md
- .changeset/friendly-terms-tan.md
- .changeset/odd-jars-provide.md
- .changeset/plenty-dingos-walk.md
- .changeset/shaggy-seas-walk.md
- .changeset/smooth-boats-change.md
- .changeset/three-mangos-rush.md
- packages/design-system/CHANGELOG.md
- packages/design-system/package.json
- packages/design-system/src/Button/index.tsx
- packages/design-system/src/Dropdown/index.tsx
- packages/design-system/src/FormMessage/FormMessage.stories.tsx
- packages/design-system/src/FormMessage/index.tsx
- packages/design-system/src/Radio/index.tsx
- packages/design-system/src/TextInput/TextInput.stories.tsx
- packages/design-system/src/TextInput/index.tsx
- packages/design-system/src/TreeDropdown/index.tsx
- packages/design-system/src/themes/default/index.css
There was an issue with radio button styles that were causing tests to fail. This PR reverts the changes that introduced those issues, and also updates release with the epic.
> fix: radio button

- .changeset/green-ravens-sip.md
- packages/design-system/src/Button/index.tsx
- packages/design-system/src/CopyToClipboard/index.tsx
- packages/design-system/src/FilePickerV2/index.tsx
- packages/design-system/src/ShowcaseCarousel/index.tsx
- packages/design-system/src/themes/default/colors.css
Supports https://github.com/appsmithorg/appsmith/issues/18052
> feat: update button states

- .changeset/beige-bags-act.md
- packages/design-system/src/Dropdown/index.tsx
- Added `left-icon-wrapper` class to the leftElement.
- Test A
- Test B
> fix: fontfamily for dropdowns.

- .changeset/friendly-dots-yell.md
- .changeset/heavy-wolves-sin.md
- packages/design-system/CHANGELOG.md
- packages/design-system/package.json
- packages/design-system/src/TextInput/index.tsx
Adds a prefix prop which accepts a string.
Locally
> feat: add a prefix prop to text input

- package.json
- yarn.lock
> chore: Dependabot vulnerabilities 

- .changeset/smooth-kiwis-remember.md
- packages/design-system/src/Icon/index.tsx
More icon changes as in https://zpl.io/B1eozpq
Manually
> feat: add more icons used in nav bar

- packages/design-system/src/MenuItem/index.tsx
- packages/design-system/src/Table/index.tsx
> Adding data test ids on a few components for using it in unit tests.
Fixes [#19495](https://github.com/appsmithorg/appsmith/issues/19495)
- Adding data test id
> This doesn't have any impact on the component. The new attribute is getting added on the DOM element as expected.
> chore: Adding data test ids on a few components

- .github/pull_request_template.md
Uses better pull request template from main repo
Chore
> chore: make pull request template better

- .changeset/pretty-ghosts-look.md
- packages/design-system/src/Collapsible/Collapsible.stories.tsx
- packages/design-system/src/Collapsible/index.tsx
Added a simple collapsible menu component.
Fixes [#169](https://github.com/appsmithorg/cloud-services/issues/169)
- Manual
> feat: collapsible component

- .changeset/clever-falcons-cry.md
- README.md
- packages/design-system-old/README.md
- packages/design-system-old/rollup.config.js
Updated readme file according to the new package names and folder changes.
- Jest
- Cypress
> fix: Readme updates for new DS

- packages/design-system/src/Text/Text.types.ts
> fix: update label types

- packages/design-system/src/__theme__/default/colors.css
- packages/design-system/src/__theme__/default/index.css
This PR adds a scale to the color blue, so that we can have multiple variables of different weights that can map to different theme variables.
> fix: blue on a scale

- .changeset/seven-chairs-swim.md
- packages/design-system-old/src/Icon/index.tsx
> chore: added arrow up icon

- .changeset/long-beds-perform.md
- packages/design-system/src/Switch/Switch.styles.tsx
- packages/design-system/src/Text/Text.stories.tsx
- packages/design-system/src/Text/Text.styles.tsx
- packages/design-system/src/Text/Text.tsx
- packages/design-system/src/Text/Text.types.ts
- packages/design-system/src/__theme__/default/colors.css
- packages/design-system/src/__theme__/default/index.css
- packages/design-system/src/__theme__/default/typography.css
Zeplin: https://zpl.io/noZY9KQ
This PR only adds font sizes to prevent layout shifting. We will be using this component only within our components for now.
> feat: add typescales to text

- .changeset/great-zebras-fold.md
- packages/design-system/src/Icon/Icon.stories.tsx
- packages/design-system/src/Icon/Icon.styles.tsx
- packages/design-system/src/Icon/Icon.tsx
- packages/design-system/src/Icon/Icon.types.ts
- packages/design-system/src/__config__/types.ts
Added size variations as per zeplin.
Fixes [#19332](https://github.com/appsmithorg/appsmith/issues/19332)
- Jest
- Cypress
> fix: Added icon size variations

- packages/design-system/src/__theme__/default/colors.css
- packages/design-system/src/__theme__/default/index.css
Guidelines: https://www.notion.so/appsmith/Colour-Guidelines-9e81cb8708314969ac29537a040c42c5
- Jest
- Cypress
> Add Testsmith test cases links that relate to …
> feat: update tokens based on the new color guidelines

- .changeset/stale-gifts-hide.md
- packages/design-system-old/src/Icon/index.tsx
Add ascending and descending remix icons
> chore: add sorting icons

- .changeset/shaggy-stingrays-drum.md
- packages/design-system/src/Callout/Callout.constants.ts
- packages/design-system/src/Callout/Callout.stories.tsx
- packages/design-system/src/Callout/Callout.styles.tsx
- packages/design-system/src/Callout/Callout.tsx
- packages/design-system/src/Callout/Callout.types.ts
- packages/design-system/src/Callout/index.ts
- packages/design-system/src/Icon/getIconByKind.tsx
- packages/design-system/src/Toast/Toast.stories.tsx
- packages/design-system/src/Toast/Toast.tsx
- packages/design-system/src/Toast/Toast.types.tsx
- packages/design-system/src/__config__/types.ts
- packages/design-system/src/__theme__/default/index.css
- packages/design-system/src/__theme__/getIconByKind.tsx
- packages/design-system/src/index.ts
Fixes https://github.com/appsmithorg/appsmith/issues/19334
Depends on https://github.com/appsmithorg/design-system/pull/375, https://github.com/appsmithorg/design-system/pull/334, https://github.com/appsmithorg/design-system/pull/333
- Jest
- Cypress
> feat: add callout

- .changeset/flat-paws-sip.md
- .changeset/flat-radios-kick.md
- .changeset/great-zebras-fold.md
- .changeset/long-beds-perform.md
- .changeset/mean-carpets-perform.md
- .changeset/moody-files-enjoy.md
- .changeset/old-ghosts-mix.md
- .changeset/olive-impalas-compare.md
- .changeset/plenty-hounds-brake.md
- .changeset/quiet-poems-boil.md
- .changeset/seven-chairs-swim.md
- .changeset/sharp-cooks-invite.md
- .changeset/sour-ghosts-train.md
- .changeset/stale-gifts-hide.md
- .changeset/witty-suns-invent.md
- packages/design-system-old/CHANGELOG.md
- packages/design-system-old/package.json
- packages/design-system/CHANGELOG.md
- packages/design-system/alpha-release.sh
- packages/design-system/package.json
- yarn.lock
Fixed css not including issue in the package
> fix: Build fix v2

- packages/design-system-old/src/Tabs/index.tsx
> Update tab title font size from 16px to 14px.
> This is to align font size wit the recent error handling changes.
Fixes # 
> fix: Update Tab title font size

- packages/design-system/src/Input/Input.stories.tsx
- packages/design-system/src/Input/Input.styles.tsx
- packages/design-system/src/Input/Input.tsx
- packages/design-system/src/Input/Input.types.tsx
- packages/design-system/src/NumberInput/NumberInput.constants.ts
- packages/design-system/src/NumberInput/NumberInput.stories.tsx
- packages/design-system/src/NumberInput/NumberInput.styles.tsx
- packages/design-system/src/NumberInput/NumberInput.tsx
- packages/design-system/src/NumberInput/NumberInput.types.ts
- packages/design-system/src/NumberInput/index.ts
- packages/design-system/src/SearchInput/SearchInput.stories.tsx
Added number input
https://github.com/appsmithorg/appsmith/issues/21251
- Jest
- Cypress …
> feat: Refactored number input

- .changeset/loud-oranges-matter.md
This PR contains an empty commit to trigger release.
> chore: trigger release

- packages/design-system/src/Callout/Callout.stories.tsx
- packages/design-system/src/Callout/Callout.tsx
- packages/design-system/src/Callout/Callout.types.ts
- packages/design-system/src/Input/Input.tsx
- packages/design-system/src/Link/Link.styles.tsx
- packages/design-system/src/Link/Link.tsx
- packages/design-system/src/Link/Link.types.tsx
- packages/design-system/src/Menu/Menu.stories.tsx
- packages/design-system/src/Menu/Menu.styles.tsx
- packages/design-system/src/Menu/Menu.tsx
- packages/design-system/src/Menu/Menu.types.ts
- packages/design-system/src/Menu/styles.css
- packages/design-system/src/NumberInput/NumberInput.tsx
- packages/design-system/src/SearchInput/SearchInput.tsx
- menu having defaultOpen because the docs page of the story would hang every time due to the length of the menu
- spread props on searchInput 
- add onClick support for Link
- add onClick support for Link in Callout 
> fix: issues during deduplication

- .changeset/wicked-scissors-appear.md
> fix: Create wicked-scissors-appear.md

- packages/design-system/src/Button/Button.styles.tsx
- packages/design-system/src/Button/Button.types.ts
- packages/design-system/src/Callout/Callout.styles.tsx
- packages/design-system/src/Callout/Callout.types.ts
- packages/design-system/src/Icon/getIconByKind.tsx
- packages/design-system/src/Link/Link.styles.tsx
- packages/design-system/src/Link/Link.types.tsx
- packages/design-system/src/Select/Select.types.ts
- packages/design-system/src/Spinner/Spinner.types.tsx
- packages/design-system/src/Tag/Tag.styles.tsx
- packages/design-system/src/Tag/Tag.types.tsx
- packages/design-system/src/Text/Text.styles.tsx
- packages/design-system/src/Text/Text.types.ts
- packages/design-system/src/Toast/Toast.types.tsx
- packages/design-system/src/ToggleButton/ToggleButton.styles.tsx
- packages/design-system/src/ToggleButton/ToggleButton.types.ts
- packages/design-system/src/__config__/types.ts
Some type names was duplicated in the code and since we started exporting types those were causing build failure. Fixed those 
- Jest
- Cypress
> fix: export type name duplication

- packages/design-system/src/ToggleButton/ToggleButton.stories.tsx
- packages/design-system/src/ToggleButton/ToggleButton.tsx
- packages/design-system/src/ToggleButton/ToggleButton.types.ts
- packages/design-system/src/ToggleGroup/ToggleGroup.constants.ts
- packages/design-system/src/ToggleGroup/ToggleGroup.stories.tsx
- packages/design-system/src/ToggleGroup/ToggleGroup.styles.ts
- packages/design-system/src/ToggleGroup/ToggleGroup.tsx
- packages/design-system/src/ToggleGroup/ToggleGroup.types.ts
- packages/design-system/src/ToggleGroup/index.ts
- packages/design-system/src/index.ts
- Added a Toggle Group component.
- Chore (housekeeping or …
> feat: added Toggle Group Component.

- packages/design-system/src/ToggleGroup/ToggleGroup.stories.tsx
Fixed story import issue.
- Jest
- Cypress
> fix: Update ToggleGroup.stories.tsx

- .changeset/tame-numbers-work.md
- packages/design-system-old/.storybook/main.js
- packages/design-system-old/.storybook/preview.js
- packages/design-system-old/.svgrrc.js
- yarn.lock
This PR fixes the icon render issue in storybook.
- Jest
- Cypress
> fix: icon not rendering in all icons page

- packages/design-system/src/Select/rc-styles.css
- packages/design-system/src/__theme__/default/index.css
Updating UI for scrollbars on DS components
Fixes https://www.notion.so/appsmith/Custom-scrollbar-css-on-DS-components-f47496d3f722441bbc1bb919d5055fa8?pvs=4
> fix: Updating UI for scrollbars on DS components

- .changeset/angry-scissors-argue.md
- packages/design-system/src/Button/Button.stories.tsx
- packages/design-system/src/Button/Button.tsx
- packages/design-system/src/Button/Button.types.ts
Adding default type for button
> fix: Adding default type for button

- packages/design-system/src/Select/Select.stories.tsx
> chore: add a story to select to have a checkbox

- packages/design-system/src/DatePicker/DatePicker.stories.tsx
- packages/design-system/src/DatePicker/DatePicker.tsx
- packages/design-system/src/DatePicker/DatePicker.types.ts
- packages/design-system/src/DatePicker/DateRangePicker.stories.tsx
- packages/design-system/src/DatePicker/styles.css
> fix: moar datepicker things

- packages/design-system/src/DatePicker/styles.css
> fix: spacing

- .changeset/fresh-zebras-brake.md
- packages/design-system/src/Toast/Toast.tsx
Fixes https://github.com/appsmithorg/appsmith/issues/24222
- Jest
- Cypress
> fix: add prop to pause on hover

- packages/design-system/.storybook/preview.js
- packages/design-system/src/DatePicker/DatePicker.stories.tsx
- packages/design-system/src/DatePicker/DateRangePicker.stories.tsx
- packages/design-system/src/Icon/Icon.stories.tsx
- packages/design-system/src/Input/Input.stories.tsx
- packages/design-system/src/Menu/Menu.stories.tsx
- packages/design-system/src/NumberInput/NumberInput.stories.tsx
- packages/design-system/src/SearchInput/SearchInput.stories.tsx
- packages/design-system/src/Select/Select.stories.tsx
- packages/design-system/src/Switch/Switch.stories.tsx
- packages/design-system/src/Tab/Tab.stories.tsx
Fixes https://www.notion.so/appsmith/Make-storybook-component-code-documentation-better-for-engineer-531936e3844a47ac9318e8c7978ca95d
Reference: https://github.com/storybookjs/storybook/issues/12596
- This change is a documentation update
- Jest
- Cypress
> docs: add code snippets

- .changeset/gorgeous-dogs-bow.md
- packages/design-system-old/src/EditableText/index.tsx
- packages/design-system-old/src/EditableTextSubComponent/index.tsx
- packages/design-system-old/src/GifPlayer/index.tsx
1. https://github.com/appsmithorg/appsmith/issues/24406
2. Old grays in gif player icon
- Jest
- Cypress
> Link issues raised during …
> fix: old gray, alignment 

- packages/design-system/package.json
PR to fix the chromatic workflow.
Fixes [#24650](https://github.com/appsmithorg/appsmith/issues/24650)
- Jest
- Cypress
> fix: Chromatic workflow

- packages/design-system/package.json
- yarn.lock
Added concurrently package, which is required for chromatic workflow script.
> Please describe the tests that …
> fix: Added concurrently package for workflows

- .changeset/eighty-roses-suffer.md
- packages/design-system/src/DatePicker/styles.css
- packages/design-system/src/Icon/Icon.provider.tsx
Added back lazy loading for icons inside icon component.
https://github.com/appsmithorg/appsmith/issues/23876
- Jest
- Cypress
> fix: Added lazy loading icon in icon component

- .github/workflows/alpha.yml
This PR fixes alpha version publishing issue.
- This …
> fix: Alpha workflow versioning fix

- .github/workflows/Lib-build-design-system.yml
- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/release.yml
- build-stories.sh
- packages/design-system-old/alpha-release.sh
- packages/design-system/alpha-release.sh
https://yarnpkg.com/cli/install#options-immutable
Fixes issue where sometimes the build does not run, and so the alpha release does not contain any packages
- Manual on …
> fix: rename all instances of frozen-lockfile to immutable

- .github/workflows/Lib-build-design-system.yml
- .github/workflows/alpha.yml
Fixes for chromatic and alpha workflow
- This change …
> fix: Chromatic and alpha workflow

- .github/workflows/Lib-build-design-system.yml
- .github/workflows/alpha.yml
Fixing failures in workflows
Fixes #https://github.com/appsmithorg/appsmith/issues/25967
> Please describe …
> fix: workflow failures

- .github/workflows/alpha.yml
Removed test comment from alpha workflow
- This …
> fix: Removed test comment

- .github/workflows/Lib-build-design-system.yml
Added fetch-depth:0 as chromatic workflow requires this
> Please describe the tests that you ran to verify …
> fix: Chromatic workflow fetch depth added

- .github/workflows/Lib-build-design-system.yml
- .github/workflows/alpha.yml
Workflows was always taking release commit to run. This PR contains the possible fix for the same.
> Please …
> fix: changed workflow refs

- packages/design-system/src/Icon/Icon.stories.tsx
Removed all icons story since a new story with icons are available and all icons page is breaking chromatic.
- Chore …
> fix: Remove all icons story

- .changeset/grumpy-bottles-travel.md
- .changeset/hungry-rivers-work.md
- packages/design-system/src/Tag/Tag.mdx
- packages/design-system/src/Tag/Tag.stories.tsx
- packages/design-system/src/Tag/Tag.styles.tsx
- packages/design-system/src/Tag/Tag.tsx
- packages/design-system/src/Tag/Tag.types.tsx
- packages/design-system/src/__theme__/default/colors.css
- packages/design-system/src/__theme__/default/index.css
This reverts commit c8a1f0e, reversing
changes made to e6f6125.
Fixes https://github.com/appsmithorg/appsmith/issues/26102
Depends on https://github.com/appsmithorg/appsmith/pull/26103
- Jest
- Cypress
> feat: revert tag and release only special and premium tags

- packages/design-system/src/Menu/Menu.styles.tsx
- packages/design-system/src/Popover/Popover.styles.tsx
- packages/design-system/src/Popover/Popover.tsx
- packages/design-system/src/Select/styles.css
- packages/design-system/src/__theme__/default/index.css
- add box shadow 
- change where scroll is
- update width and height 
- header stays sticky on scroll
- update category tokens for border
Depends on https://github.com/appsmithorg/appsmith/pull/26072/
- Jest
- Cypress
https://github.com/appsmithorg/design-system/pull/590#issuecomment-1683727274
https://github.com/appsmithorg/design-system/pull/590#issuecomment-1686175670
> feat: change some styles in popover

- packages/design-system/src/ToggleButton/ToggleButton.mdx
- packages/design-system/src/ToggleButton/ToggleButton.stories.tsx
- packages/design-system/src/ToggleButtonGroup/ToggleButtonGroup.stories.tsx
Added documentation for the size variant of the toggle button.
>
Fixes https://github.com/appsmithorg/appsmith/issues/26280
> here don't break existing flows. Link the …
> chore: update ToggleButton.mdx

- packages/design-system/src/Popover/Popover.mdx
- packages/design-system/src/Popover/Popover.stories.tsx
Fixes https://github.com/appsmithorg/appsmith/issues/26729
- This change is a documentation update
- Jest
- Cypress
> feat: Add size and scroll guidelines to popover documentation 

- .github/workflows/chromatic.yml
Fixes https://github.com/appsmithorg/appsmith/issues/26702
> chore: set up chromatic workflows

- .github/workflows/chromatic.yml
> chore: use correct flag for yarn 1

- .github/workflows/chromatic.yml
> chore: check out branch specifically for install job

- packages/design-system/src/Documentation/ContributionChecklist.mdx
Added contribution checklist for the design system repo.
Fixes #https://github.com/appsmithorg/appsmith/issues/26108
- Jest
- Cypress
> feat: Added contribution checklist

- packages/design-system/fileTransformer.js
- packages/design-system/src/Divider/Divider.test.tsx
- packages/design-system/src/Icon/Icon.provider.tsx
- packages/design-system/src/Icon/Icon.stories.tsx
- packages/design-system/src/Icon/Icon.test.tsx
Closes https://github.com/appsmithorg/appsmith/issues/26905
Closes https://github.com/appsmithorg/appsmith/issues/26907
- Jest
- Cypress
> chore: add tests for divider and icon

- packages/design-system/src/Link/Link.test.tsx
Fixes https://github.com/appsmithorg/appsmith/issues/24158
- Jest
- Cypress
> chore: add unit tests for link

- packages/design-system/.storybook/main.js
- packages/design-system/rollup.config.mjs
- packages/design-system/src/custom.d.ts
Added support for css module in new design system library.
Fixes #https://github.com/appsmithorg/appsmith/issues/27526
- Jest
- Cypress
> feat: Added CSS module support

- packages/design-system/plop-templates/component.mdx.hbs
> fix: issue with plop template and mdx

- packages/design-system/src/List/List.mdx
Changed from small > medium because we don't have a small variant yet.
>
> every PR in the design-system repository should have a corresponding PR in the appsmith repository to ensure that changes …
> chore: Update List.mdx

- .changeset/afraid-kids-stare.md
- packages/design-system-old/src/assets/icons/ads/workflows.svg
- packages/design-system/src/Icon/Icon.provider.tsx
- packages/design-system/src/__assets__/icons/ads/workflows-mono.svg
- packages/design-system/src/__assets__/icons/ads/workflows.svg
Updated current icon for workflows and created a new monochrome icon also as per designs.
Thread: https://theappsmith.slack.com/archives/C05QG0J87UL/p1710151585419079?thread_ts=1709815308.045609&cid=C05QG0J87UL
Fixes [#31357](https://github.com/appsmithorg/appsmith/issues/31357)
- Jest
- Cypress
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped …
> feat: new workflow icons
