appsmithorg/design-system

- package.json
- yarn.lock
Fixed dependabot alert for trim, glob-parent, trim-newlines packages.
Fixes [#15101](https://github.com/appsmithorg/appsmith/issues/15101)
> fix: Dependabot security alert fixes

- .changeset/lemon-ladybugs-drop.md
- packages/design-system/README.md
- packages/design-system/src/DropdownV2/DropdownV2.stories.tsx
- packages/design-system/src/DropdownV2/index.tsx
- packages/design-system/src/HighlightText/HighlightText.stories.tsx
- packages/design-system/src/HighlightText/index.tsx
- packages/design-system/src/SearchComponent/SearchComponent.stories.tsx
- packages/design-system/src/SearchComponent/index.tsx
- packages/design-system/src/themes/default/colors.css
- packages/design-system/src/themes/default/index.css
This PR will 
- Migrate DropdownV2 from the ads to here 
- Add a flag that enables search according to [the designs in figma](https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=10508%3A30677)
- Migrate SearchComponent and HighlightText components because they are dependencies on this feature
Fixes #[14969](https://github.com/appsmithorg/appsmith/issues/14969)
I've tested this out manually on the storybook 
- full text match 
- random substrings
- substrings include spaces
- substrings include upper and lower case
- all of the above
- limitation: the string …
> feat: migrate dropdown v2

- package.json
- yarn.lock
This PR contains the fix for nth-check package. nth-check package had a Regular Expression Denial of Service (ReDoS) vulnerability for versions below 2.0.1.
Fixes [#15254](https://github.com/appsmithorg/appsmith/issues/15254)
> fix: Added resolution for patched nth check package

- .changeset/cold-donuts-bow.md
- packages/design-system/src/SearchComponent/index.tsx
This PR enables the 'cross' icon functionality. I had commented it out earlier during the migrations because icons weren't available in the ds repo yet 😓 
Fixes the tests on [this pr](https://github.com/appsmithorg/appsmith/pull/15081) from failing
Storybook!
> fix: enable cross icon

- package.json
- yarn.lock
Fixed dependabot alert for terser ReDoS venerability 
Fixes [#15496](https://github.com/appsmithorg/appsmith/issues/15496)
> fix: terser dependabot alert for ReDoS

- .changeset/blue-lies-help.md
- packages/design-system/src/DropdownV2/DropdownV2.stories.tsx
- packages/design-system/src/DropdownV2/index.tsx
There were two exports from the design system package, both called `Dropdown`. Our braking page was importing the wrong one (because it was declared first).
Fixed by renaming all the 'Dropdown' components that refer to DropdownV2 to DropdownV2. 
Fixes breaking tests on #15081
> fix: clashing dropdown exports

- .changeset/curvy-clouds-guess.md
- packages/design-system/src/LabelWithTooltip/index.tsx
- packages/design-system/src/ListSegmentHeader/ListSegmentHeader.test.tsx
- packages/design-system/src/NotificationBanner/NotificationBanner.test.tsx
- packages/design-system/src/index.ts
This PR will add a couple of exports, missing test files, fix variant names etc that will allow https://github.com/appsmithorg/appsmith/pull/15562 and https://github.com/appsmithorg/appsmith/pull/15722 to go through. 
Tested by running yarn build on local, and using yalc.
> fix: import changes support

- .changeset/neat-tigers-sparkle.md
- packages/design-system/src/TreeDropdown/index.tsx
Package build was failing because of Tree Dropdown props intent and icon type was not correct. Fixed those two in this PR.
Fixes [#15772](https://github.com/appsmithorg/appsmith/issues/15772)
- Tested the build in local
> fix: Treedropdown icon and intent prop type

- .changeset/curvy-rules-shave.md
- packages/design-system/src/ScrollIndicator/index.tsx
> feat: Adds showScrollbarOnlyOnHover functionality as a property to ScrollIndicator

- .changeset/polite-lions-search.md
- packages/design-system/src/Checkbox/index.tsx
- packages/design-system/src/ScrollIndicator/index.tsx
Fixes issue where Table widget was showing scrollbar even when not in focus. Made by @souma-ghosh 
Fixes [#3744](https://github.com/appsmithorg/appsmith/issues/3744)
> fix: Table Widget shows scrollbar when not in focus

- .changeset/large-horses-smell.md
- packages/design-system/src/DialogComponent/index.tsx
- packages/design-system/src/TreeDropdown/TreeDropdown.stories.tsx
- packages/design-system/src/TreeDropdown/index.tsx
The line height variable was used directly without appending the px value to it. When a value is used without a unit, it is assumed to be in rem.
> fix: issue with line height in TableDropdown

- .changeset/cuddly-lions-punch.md
- packages/design-system/.storybook/preview.js
- packages/design-system/src/Icon/Icon.stories.tsx
This PR adds a story that displays a list of all available icons in the system for easy perusal
Locally on storybook
> feat: add all icon stories

- .changeset/strong-penguins-change.md
- packages/design-system/src/IconSelector/index.tsx
Destructured props to use onSelect inside onClick, this will fix the issue of throwing withConfig error in local development
Fixes [#16390](https://github.com/appsmithorg/appsmith/issues/16390)
- Bug fix (non-breaking change which fixes an issue)\
- Tested in local using yalc
> fix:IconSelector onSelect function failing in local

- .changeset/late-swans-whisper.md
- packages/design-system/src/DisplayImageUpload/index.tsx
> fix: issue with default image being zoomed in on the Display Image Upload component

- .changeset/fifty-goats-march.md
- packages/design-system/src/AppIcon/AppIcon.stories.tsx
AppIcon story was not showing up because of the wrong import of Size. have fixed in this PR and the story is now showing up.
Fixes [#16568](https://github.com/appsmithorg/appsmith/issues/16568)
> fix: AppIcon story not showing in storybook

- .changeset/stale-bees-matter.md
- packages/design-system/src/CalloutV2/index.tsx
Migrating CalloutV2 - destructure onClick prop, use better prop types
> fix: destructure onClick on migrating CalloutV2

- .changeset/plenty-dingos-walk.md
- packages/design-system/src/constants/typography.ts
Remove bad ascii character double quotes.
Fixes #17645
By releasing an alpha version on the dp
> fix: issue with font of toasts on windows machines

- .changeset/shaggy-seas-walk.md
- packages/design-system/src/FilePickerV2/index.tsx
Fixes https://github.com/appsmithorg/appsmith/issues/17584
Locally by developer
> fix: destructure file picker functions so that they don't throw errors on local

- packages/design-system/src/TreeDropdown/index.tsx
The options in the tree dropdown were not updating when the options tree was getting updated. Adding a `useEffect` takes care of the issue.
- Manually
> fix: Update options in the tree dropdown when the list gets updated

- .changeset/breezy-parents-know.md
- .changeset/giant-keys-burn.md
- packages/design-system/src/Button/index.tsx
- packages/design-system/src/ButtonTab/ButtonTab.stories.tsx
- packages/design-system/src/Checkbox/index.tsx
- packages/design-system/src/Dropdown/Dropdown.stories.tsx
- packages/design-system/src/Dropdown/index.tsx
- packages/design-system/src/FilePickerV2/index.tsx
- packages/design-system/src/Link/Link.stories.tsx
- packages/design-system/src/Link/index.tsx
- packages/design-system/src/ListSegmentHeader/index.tsx
- packages/design-system/src/Radio/index.tsx
- packages/design-system/src/SearchComponent/index.tsx
- packages/design-system/src/Switch/index.tsx
- packages/design-system/src/Table/Table.stories.tsx
- packages/design-system/src/Tabs/Tabs.stories.tsx
- packages/design-system/src/TagInput/TagInput.stories.tsx
- packages/design-system/src/TagInput/index.tsx
- packages/design-system/src/Text/index.tsx
- packages/design-system/src/TextInput/TextInput.stories.tsx
- packages/design-system/src/TreeDropdown/index.tsx
- packages/design-system/src/constants/typography.ts
- packages/design-system/src/index.ts
- packages/design-system/src/themes/default/colors.css
- packages/design-system/src/themes/default/index.css
- packages/design-system/src/themes/default/themables.css
Fixes issues with https://github.com/appsmithorg/appsmith/pull/17740
- underline no longer breaks for descenders
- focus styles are only activated when the element is accessed via keyboard 
- Link now explicitly accepts a type (and uses it to set font size)
- more comments on Link! explaining some css decisions. Always a good thing. 
- on the storybook
- on the main app via yalc 
- on the main app via alpha release
> fix: update hover, focus, type styles on link

- .changeset/five-gorillas-chew.md
- packages/design-system/src/Radio/index.tsx
Fixed triggering radio button on change event twice.
Fixes [#18026](https://github.com/appsmithorg/appsmith/issues/18026)
> fix: multiple on change trigger in radio component

- .changeset/tiny-parents-jump.md
- packages/design-system/src/Dropdown/index.tsx
- Add class name to the left element of the dropdown component
- Tested on Storybook
> fix: added classname to leftElement

- .changeset/beige-bags-act.md
- .changeset/clever-shoes-repeat.md
- .changeset/green-ravens-sip.md
- .changeset/heavy-wolves-sin.md
- .changeset/mighty-pants-grow.md
- packages/design-system/CHANGELOG.md
- packages/design-system/package.json
- packages/design-system/src/TextInput/index.tsx
Text Input component was not triggering validator function when the defaultValue is updated by props. This PR fixes the same.
Fixes [#17393](https://github.com/appsmithorg/appsmith/issues/17393)
- Tested in local using yalc
> fix: Text input not triggering validation on defaultValue change

- .changeset/friendly-dots-yell.md
- packages/design-system/src/Button/index.tsx
- packages/design-system/src/Icon/index.tsx
> Adding new icons for using them on the audit logs page for Granular Access Control
Fixes [#18487](https://github.com/appsmithorg/appsmith/issues/18487)
- Addition of icons
> Checked locally on storybook
> chore: Adding new icons for using them on the audit logs page for Granular Access Control

- .changeset/in-app-embed-settings-icons.md
- packages/design-system/src/Icon/index.tsx
Add icons used in in-app-embed settings https://app.zeplin.io/project/6310825e7f4577131f79df64/dashboard
Manually
> chore: add icons to be used in-app-embed settings

- .changeset/twenty-owls-perform.md
- packages/design-system/src/Button/index.tsx
- packages/design-system/src/Icon/index.tsx
> Adding delete row icon for Access control upgrade page
Fixes [#19072](https://github.com/appsmithorg/appsmith/issues/19072)
> Checked the icon locally
> chore: Add delete row icon for Access control upgrade page

- .changeset/proud-lions-search.md
- packages/design-system/src/Tabs/Tabs.stories.tsx
- packages/design-system/src/Tabs/index.tsx
> Setting the active tab only via the onSelect function using props, if present, else setting it via the component state.
Fixes [#19088](https://github.com/appsmithorg/appsmith/issues/19088)
- Test A
- Test B
> fix: Setting the active tab only via onSelect function, if present in props

- .changeset/beige-wombats-destroy.md
- packages/design-system/alpha-release.sh
The issue: With context switching, sometimes one forgets what alpha release number belongs to which commit (and therefore contains which change). This PR aims to fix that by also tagging our alpha releases.
> feat: tag the latest commit with the alpha tag created

- .changeset/real-eyes-drive.md
- packages/design-system/src/SnippetButton/index.tsx
Some tertiary buttons were missed out when closing https://github.com/appsmithorg/appsmith/issues/18052, not sure why. This PR updates them.
> feat: update snippet button from 3ry to 2ry

- .changeset/weak-items-dress.md
- packages/design-system/src/Table/index.tsx
> Removing tooltip on table header as it is not part of our design system.
Fixes [#19263](https://github.com/appsmithorg/appsmith/issues/19263)
> Tested in storybook locally. The tooltip is not seen on hover now, as expected.
> fix: Removing tooltip on table header as it is not part of our design system

- packages/design-system/rollup.config.mjs
Fixed rollup build failure because of wrong index file mentioned in roll up configuration.
- Jest
- Cypress
> fix: Rollup build failure fixed for new DS

- vercel.json
This should get the `/old` path working.
> fix: Disable SPA fallback on Vercel

- build-stories.sh
- vercel.json
A few improvements to the deployment:
1. Move build configuration from Vercel UI to the `vercel.json`, so that
1. The code maintainers can own the build process.
2. The build configuration is also version-controlled.
3. Different branches can have different build commands, useful when a PR is changing the build, like we recently needed this.
2. Move deployment to `bom1` region, since that's where it'll be accessed most from. Please correct me if this assumption is incorrect, and I'll remove that configuration.
3. Updated build script to:
1. Produce less verbose output. Vercel doesn't show build output more than the last 2000 lines. The current output means that this is useless since they are all lines about 1% done, 2% done etc. So we reduce verbosity to get more compact and useful …
> ci: Move build configuration to this repo from Vercel UI

- packages/design-system/src/Text/Text.types.ts
This PR will allow Text to be used as a label and have children that are components. This increases the place Text can be used, increasing the themability of the system. 
- Jest
- Cypress
> fix: text can now have components as children

- packages/design-system/src/__theme__/default/index.css
Remove the gap between the component and the outline ring, as per https://theappsmith.slack.com/archives/C045A6F2GGG/p1675836512007859
> fix: remove gap

- .github/workflows/test-build-docker-image.yml
Preventing the test/build/push workflow from running on every branch because pollutes the notifications and eats into ci minutes.
- Jest
- Cypress
> chore: change the trigger for the workflow

- .changeset/dry-bugs-attack.md
- packages/design-system-old/src/Table/index.tsx
> Adding the support for row expansion on the Table component.
Fixes [#21081](https://github.com/appsmithorg/appsmith/issues/21081)
Depends on [#1147](https://github.com/appsmithorg/appsmith-ee/pull/1147)
> every PR in the design-system repository should have a corresponding PR in the appsmith repository to ensure that changes here don't break existing flows. 
> Link the corresponding PR here to trigger pulls and prevent accidental merging.
> This has been tested on storybook and has no effects on the table component. Only if we use the expansion property by sending subRows to the data, will the expansion feature work.
> chore: Adding the support for row expansion on the Table component

- .changeset/bright-icons-chew.md
- packages/design-system-old/package.json
- packages/design-system/package.json
_TODO:_ once this is merged and published, this needs a PR in `appsmithorg/appsmith` to bump the package version.
This PR adds the `sideEffects: false` flag to `package.json`s. When applied to `appsmithorg/appsmith` on top of https://github.com/appsmithorg/appsmith/pull/20964, this makes the bundle 680 minified kB smaller (8.14 → 7.46 minified MB).
How does this work?
Webpack isn’t smart enough to figure out when importing a module will cause side effects (eg a console log, or a network request) vs when it won’t. So, by default, webpack keeps every module in the bundle (and just tries to remove unused consts/functions/classes instead).
Sometimes, this backfires. For example, if you have code like
```js
// some-file.js
import { Button } from "design-system"
console.log(Button)
// …
```
> perf: mark design system modules as side-effect-free

- .changeset/chilled-pets-sin.md
- packages/design-system-old/package.json
- packages/design-system-old/src/AppIcon/index.tsx
- packages/design-system-old/src/ColorPicker/index.tsx
- packages/design-system-old/src/ControlIcons/index.tsx
- packages/design-system-old/src/DisplayImageUpload/index.tsx
- packages/design-system-old/src/Dropdown/index.tsx
- packages/design-system-old/src/FilePickerV2/index.tsx
- packages/design-system-old/src/Icon/index.tsx
- packages/design-system-old/src/LabelWithTooltip/index.tsx
- packages/design-system-old/src/SearchComponent/index.tsx
- packages/design-system-old/src/Table/index.tsx
- packages/design-system-old/src/index.ts
- packages/design-system-old/src/utils/icon-loadables.tsx
- packages/design-system/package.json
- packages/design-system/src/Icon/Icon.provider.tsx
- packages/design-system/src/Icon/loadables.tsx
- yarn.lock
This PR is easier to review commit-by-commit.
This pull request
- code-splits all `.svg` and `remix` icons away, while retailing their styleability
- and sets up reusable `importSvg` and `importRemix` wrappers for code-splitting icons (I’m happy to bikeshed on the name if you have better ideas!)
Traditionally, in HTML, there are two ways to handle SVG graphics:
- one is to emit every SVG image as a separate `.svg` file – and then use the `<img>` tag to load it
- and another one is to render every SVG straight into HTML, using the `<svg>` tag
The second approach is more powerful, as it allows to style SVG images with CSS. However, in client-rendered apps, it also means bundling every SVG image into the bundle, as it’s _the bundle_ that generates HTML and must know how to render SVGs into …
> perf(icons): load icons on-demand

- packages/design-system-old/src/Button/index.tsx
Check whether button is disabled before executing on click.
Fixes https://github.com/appsmithorg/appsmith/issues/13093
- Jest
- Cypress
> fix: button disabled check for on click

- .changeset/cool-flies-perform.md
- packages/design-system/src/Divider/Divider.styles.tsx
Fixes issue with divider looking starkly different from borders because divider was implemented using a div, despite using the same colors and dimensions. 
Before: 
After: 
This is important because sometimes we use dividers and borders interchangably.
> fix: divider width and color

- .changeset/tender-readers-scream.md
- packages/design-system/src/Button/Button.styles.tsx
- packages/design-system/src/Callout/Callout.styles.tsx
- packages/design-system/src/Callout/Callout.tsx
- packages/design-system/src/Tag/Tag.styles.tsx
- packages/design-system/src/Tag/Tag.tsx
Fixes issue with clashing background for buttons on colored backgrounds.
https://theappsmith.slack.com/archives/C045A6F2GGG/p1680058760274329?thread_ts=1677753863.496299&cid=C045A6F2GGG
> fix: button blend mode

- .changeset/tasty-lamps-cover.md
- packages/design-system-old/src/Icon/index.tsx
> Importing and adding the external link line icon from remixicon to use in the invite modal for the upgrade button.
Fixes [#20578](https://github.com/appsmithorg/appsmith/issues/20578)
> chore: Importing and adding the external link line icon from remixicon

- .changeset/hot-foxes-tickle.md
- packages/design-system-old/src/DisplayImageUpload/index.tsx
- Since we are using uppy in `DisplayImageUpload` component and not exposing a way for the user to control what `options` they want with uppy, for airgapped instances we want to disable the informer which show `No internet connection`. 
- So just gave control to user for that particular option alone. 
Fixes #463 
Media:
https://user-images.githubusercontent.com/74818788/233578785-d43b89d5-39b4-4300-912e-46c0539727a6.mov
Depends on [#22366](https://github.com/appsmithorg/appsmith/issues/22366)
> Add Testsmith test …
> chore: give control to user to enable/disable uppy informer

- packages/design-system-old/.storybook/main.js
- packages/design-system-old/package.json
- packages/design-system-old/src/utils/icon-loadables.tsx
- packages/design-system/.storybook/main.js
- packages/design-system/package.json
- packages/design-system/src/Icon/loadables.tsx
- yarn.lock
This PR:
- adds error handling for cases when a code-split icon fails to load. Now, if we fail to load the icon (eg due to poor network conditions), we’ll log a warning and render an empty SVG instead
- fixes icon rendering in Storybook (which was broken because Storybook’s webpack config lacked the `@svgr/webpack` loader that the main app has)
- Manual on storybook:
- faked a network error and ensured an empty svg renders
- ensured all icons render correctly with the new webpack config
> fix(icons): add error handling + fix Storybook rendering

- .changeset/kind-pugs-dress.md
- packages/design-system/src/Input/Input.tsx
Updating the click action on input label to remove focus from input box
Fixes https://www.notion.so/appsmith/Clicking-next-to-the-Input-labels-does-not-remove-focus-from-inputs-a5a7f50c71d941998b1d0a11380ea19f?pvs=4
> fix: Updating the click action on input label to remove focus from input box

- .changeset/tasty-ears-fly.md
- packages/design-system/src/Tooltip/Tooltip.css
Updating CSS for tooltip to fix position shift issue
Fixes https://www.notion.so/appsmith/First-time-Tooltip-position-is-undesirable-833215bf50a548dd836303835ae02d46?pvs=4
> fix: Updating CSS for tooltip to fix position shift issue

- packages/design-system-old/src/EditableTextSubComponent/index.tsx
- packages/design-system-old/src/EditableTextWrapper/index.tsx
1. Removes red background on error (fixes https://github.com/appsmithorg/appsmith/issues/24098)
2. Changes saving state icon to use new standard `loader` icon (fixes https://github.com/appsmithorg/appsmith/issues/24112)
Depends on https://github.com/appsmithorg/appsmith/pull/24342
- Jest
- Cypress
> fix: editable text

- .changeset/fifty-birds-occur.md
- packages/design-system/src/SearchInput/SearchInput.tsx
- packages/design-system/src/Select/styles.css
What this PR fixes:
1. Search input, after clicking on clear icon, looses the focus.
2. Select component option styles was getting overridden by WDS tree select component.
Fixes [#24475](https://github.com/appsmithorg/appsmith/issues/24475), [#24459](https://github.com/appsmithorg/appsmith/issues/24459)
https://github.com/appsmithorg/design-system/assets/87797149/92f99d08-a4c4-4ea3-a57f-2000bea62a62
- Jest
- Cypress
> Link …
> fix: Search input focus issue and select styles specificity

- .changeset/curly-cooks-enjoy.md
- packages/design-system/src/NumberInput/NumberInput.tsx
- packages/design-system/src/NumberInput/NumberInput.types.ts
This PR fixed the number input suffix getting added twice in controlled integration. Along with this fix, improvements like ref passing, optimising code structure and types changes also added.
Fixes #https://github.com/appsmithorg/appsmith/issues/24819
- Jest
- Cypress
> …
> fix: Number input suffix issue

- .changeset/selfish-ducks-march.md
- packages/design-system-old/src/DisplayImageUpload/Dashboard.tsx
- packages/design-system-old/src/DisplayImageUpload/index.tsx
This PR code-splits the `DisplayImageUpload` dashboard to make and [Uppy](https://uppy.io/) load on demand. Together with https://github.com/appsmithorg/appsmith/pull/24969, this shaves ~200 minified kBs off the bundle size.
While the dashboard is loading, we now render the spinner component:
> perf(DisplayImageUpload): code-split Uppy away

- .changeset/curly-donuts-invent.md
- packages/design-system/src/Icon/Icon.provider.tsx
Adding link-unlink icon from remixicon-react
Fixes [#25266](https://github.com/appsmithorg/appsmith/issues/25266)
Depends on [#25398](https://github.com/appsmithorg/appsmith/pull/25398)
> chore: Adding link-unlink icon from remixicon-react

- .changeset/fifty-planets-repeat.md
- packages/design-system/src/Icon/Icon.provider.tsx
Adding user settings line icon from remixicon react
Fixes [#25270](https://github.com/appsmithorg/appsmith/issues/25270)
Depends on [#25404](https://github.com/appsmithorg/appsmith/pull/25404)
> chore: Adding user settings line icon from remixicon react

- .changeset/rude-cooks-tease.md
- packages/design-system/src/Button/Button.mdx
- packages/design-system/src/DesignTokens.mdx
- packages/design-system/src/Input/Input.mdx
- packages/design-system/src/Link/Link.mdx
- packages/design-system/src/Modal/Modal.mdx
- packages/design-system/src/Select/Select.mdx
- packages/design-system/src/Toast/Toast.mdx
This PR makes a distinction between further reading for developers and references used while creating the documentation
- Jest
- Cypress
> docs: separate resources from references

- .github/workflows/alpha.yml
- .github/workflows/generate-alpha.yml
Added workflow to generate alpha version from slash command.
`/generate-alpha`
Fixes #
- Jest
- Cypress
> ci: Added generate alpha command workflow

- .github/workflows/alpha.yml
Fixed the generate alpha workflow issues,
- Not generating build from latest commit
- Published version is not getting commented
Fixes #https://github.com/appsmithorg/appsmith/issues/25902
- Jest
- Cypress
> fix: Generate alpha workflow

- .changeset/stale-drinks-hide.md
- packages/design-system/src/Collapsible/Collapsible.tsx
Pretty simple, we are changing the toggle arrow directions of the collapsible widget from up/down to down/right to match other collapsible on the entity explorer such as widgets/pages/datasources etc.
Fixes #587
- Jest
- Cypress
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped …
> fix: change collapsible toggle arrow directions from up/down to down/right

- .changeset/moody-fans-warn.md
- packages/design-system/src/DatePicker/styles.css
- packages/design-system/src/Menu/Menu.styles.tsx
- packages/design-system/src/Popover/Popover.styles.tsx
- packages/design-system/src/Select/styles.css
- packages/design-system/src/__theme__/default/index.css
When the [category token was changed for popover border](https://github.com/appsmithorg/design-system/pull/590/commits/0e7994a6cbed276614dcea8f0a576b39092b829a), the divider color was also changed from default-border to default border muted. However, this dependency didn't show up in my editor as a "usage" because the token is used inside a string. Since this change was unintentional and won't work for our platform, this PR creates two tokens for content-border, one for surface (which divider and menu divider uses), and one for container (which menu, select, popover, and date picker uses). 
- Jest
- Cypress
> Link …
> fix: divider colors

- .changeset/angry-news-care.md
- packages/design-system-old/src/TagInput/index.tsx
Updating tag input value to original value, when the form is reset
Fixes [#27671](https://github.com/appsmithorg/appsmith/issues/27671)
Depends on [#27681](https://github.com/appsmithorg/appsmith/pull/27681) [#2485](https://github.com/appsmithorg/appsmith-ee/pull/2485)
> fix: Updating tag input value to original value, when the form is reset

- .changeset/thin-zebras-sneeze.md
- packages/design-system/src/Banner/Banner.stories.tsx
- packages/design-system/src/Banner/Banner.styles.tsx
- packages/design-system/src/Banner/Banner.tsx
- packages/design-system/src/Banner/Banner.types.ts
- packages/design-system/src/Banner/index.ts
- packages/design-system/src/Callout/Callout.constants.ts
- packages/design-system/src/Callout/Callout.stories.tsx
- packages/design-system/src/Callout/Callout.tsx
- packages/design-system/src/Callout/Callout.types.ts
- packages/design-system/src/index.ts
This PR has added the new banner component which internally uses callout since the functionalities and styles are same almost.
Fixes #https://github.com/appsmithorg/appsmith/issues/27605
- Jest
- Cypress
> feat: Added banner component

- packages/design-system/rollup.config.mjs
- packages/design-system/src/custom.d.ts
After making postcss changes for css module, rc select classes was also getting appended with unique id. This caused the issue of breaking select component UI.
Fixes #https://github.com/appsmithorg/appsmith/issues/27988
- Jest
- Cypress
> fix: rc select ui broken after css module update

- .changeset/perfect-mice-refuse.md
- packages/design-system/src/List/List.stories.tsx
- packages/design-system/src/List/List.styles.tsx
- packages/design-system/src/List/List.tsx
- packages/design-system/src/List/List.types.tsx
Fixes https://github.com/appsmithorg/appsmith/issues/28212
> feat: allow react node for start icon in ListItem

- .changeset/fluffy-badgers-love.md
- packages/design-system-old/src/Table/index.tsx
Added z-index to sticky thead to avoid row components overlapping.
Fixes https://github.com/appsmithorg/appsmith/issues/28014
- Jest
- Cypress
> fix: Added z-index for table head

- packages/design-system/package.json
- packages/design-system/src/Table/Table.constants.ts
- packages/design-system/src/Table/Table.stories.tsx
- packages/design-system/src/Table/Table.styles.tsx
- packages/design-system/src/Table/Table.tsx
- packages/design-system/src/Table/Table.types.ts
- packages/design-system/src/Table/index.ts
- packages/design-system/src/Table/reset.css
- packages/design-system/src/__theme__/default/index.css
- packages/design-system/src/index.ts
- yarn.lock
This PR adds table component to ADS v2. Table component will be using ec-table internally.
Fixes https://github.com/appsmithorg/appsmith/issues/27771
- Jest
- Cypress
> feat: Added table component

- packages/design-system/src/Text/Text.stories.tsx
- packages/design-system/src/Text/Text.styles.tsx
- packages/design-system/src/Text/Text.tsx
- packages/design-system/src/Text/Text.types.ts
Added editable component.
Fixes https://github.com/appsmithorg/appsmith/issues/28096
- Jest
- Cypress
> feat: Added editable text

- .changeset/dull-donkeys-play.md
- .changeset/fluffy-badgers-love.md
- .changeset/perfect-mice-refuse.md
- .changeset/stale-parrots-learn.md
- packages/design-system-old/CHANGELOG.md
- packages/design-system-old/package.json
- packages/design-system/CHANGELOG.md
- packages/design-system/package.json
- packages/design-system/src/List/List.constants.ts
- packages/design-system/src/List/List.styles.tsx
- packages/design-system/src/List/List.tsx
- packages/design-system/src/List/List.types.tsx
* Line height fix
* Added className support for List
* Added className & wrapperClassName support for ListItem
Fixes https://github.com/appsmithorg/appsmith/issues/28458
- Jest
- Cypress
> fix: List component line height class name

- packages/design-system/src/Input/Input.constants.ts
- packages/design-system/src/Input/Input.styles.tsx
- packages/design-system/src/Input/Input.tsx
- packages/design-system/src/Input/Input.types.tsx
- packages/design-system/src/NumberInput/NumberInput.tsx
- packages/design-system/src/NumberInput/NumberInput.types.ts
1. Disable Icon clicks on NumberInput upon min-max violations.
2. Add another prop to disable text input only. ``disableTextInput``.
> chore: Disable Icon clicks on NumberInput upon min-max violations

- .changeset/shiny-horses-walk.md
- packages/design-system/src/Documentation/components/CodeBlock.tsx
Fixes https://github.com/appsmithorg/appsmith/issues/26847
Removed 'Tooltip' component and replaced it with 'Icon' component (copy).
- Tested for responsiveness
> feat: replaced tooltip with copy button

- .changeset/few-shrimps-appear.md
- packages/design-system/src/Checkbox/Checkbox.constants.ts
- packages/design-system/src/Checkbox/Checkbox.styles.tsx
- packages/design-system/src/Checkbox/Checkbox.tsx
- packages/design-system/src/Radio/Radio.constants.ts
- packages/design-system/src/Radio/Radio.styles.tsx
- packages/design-system/src/Radio/Radio.tsx
Radio button and Checkbox was rendering the radio/checkbox twice when a tag component is passed as children. This was because of the css selectors inside these two component where checking for any span element. Added respective classnames to these to fix the issue.
Fixes https://github.com/appsmithorg/appsmith/issues/28889
- Jest
- Cypress
> fix: Radio, Checkbox - child span issue

- .changeset/smart-socks-learn.md
- packages/design-system/src/Input/Input.styles.tsx
- packages/design-system/src/SearchInput/SearchInput.styles.tsx
Previously, Form input elements had different sm sizes.
Button             -> 24px
Datepicker      -> 22px
Input                -> 22px
Search Input   -> 28px
Number Input -> 22px
Select              -> 24px
This PR updates all these to 24px.
Fixes https://github.com/appsmithorg/appsmith/issues/34599
- Jest
- Cypress
> fix: Updated sm size for DatePicker, Input, Number Input, and Search Input
